name: time_management
description: "App that helps you organize your day."
publish_to: 'none'
version: 0.2.1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  extended_text: ^15.0.2
  file_picker: ^10.3.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^19.4.1
  flutter_native_splash: ^2.4.6
  fluttertoast: ^8.2.12
  get: ^4.7.2
  intl: ^0.20.2
  open_file_plus:
    git:
      url: https://github.com/postflow/open_file_plus.git
      ref: main
  path: ^1.9.1
  shared_preferences: ^2.5.3
  sqflite: ^2.4.2
  timezone: ^0.10.1
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/png/

  fonts:
  - family:  AppIcons
    fonts:
    - asset: assets/icons/app_icons.ttf

  - family:  Crimson Pro
    fonts:
    - asset: assets/fonts/CrimsonPro-Italic.ttf
      style: italic
    - asset: assets/fonts/CrimsonPro.ttf

